// REDUX ACTION TYPES
export const TICK = 'TICK'
export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const RESET = 'RESET'

export const ActionTypes = {
  SIGN_IN:'SIGN_IN',
  SIGN_OUT:'SIGN_OUT',
  SET_NAV:'SET_NAV',
  SET_ADVERTS:'SET_ADVERTS',
  SET_SINGLE_ADVERT:'SET_SINGLE_ADVERT',
  REMOVE_SINGLE_ADVERT: "REMOVE_SINGLE_ADVERT",
}
